name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
filter-by-commitish: true
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'feat'
      - 'enhancement'
      - 'refactoring'
      - 'test'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🌐 Translations'
    labels:
      - 'translations'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'bld'
      - 'dependencies'
      - 'documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor
template: |
  ## Changes

  $CHANGES
  
  ## Installation command
  docker run -itd -p 8005:8005 --restart always --name github-env-manager ghcr.io/am-i-b-v/github-env-manager:v$RESOLVED_VERSION
