name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
filter-by-commitish: true
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'feat'
      - 'enhancement'
      - 'refactoring'
      - 'test'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🌐 Translations'
    labels:
      - 'translations'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'bld'
      - 'dependencies'
      - 'documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor
template: |
  ## Changes

  $CHANGES
  
  ### Quick Start

  #### 🚀 One-Command Installation (Recommended)
  
  ```bash
  # Install and run with automatic port selection
  curl -fsSL https://raw.githubusercontent.com/AM-i-B-V/github-env-manager/main/install.sh | bash
  ```
  
  #### 🐳 Manual Docker Installation
  
  ```bash
  docker run -itd -p 8005:8005 --restart always --name github-env-manager amibotuser/github-env-manager:v$RESOLVED_VERSION
  ```
