name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧹 Maintenance"
    labels:
      - "chore"
      - "dependencies"
      - "maintenance"
  - title: "📚 Documentation"
    labels:
      - "documentation"
      - "docs"
  - title: "🔧 CI/CD"
    labels:
      - "ci"
      - "cd"
      - "workflow"
      - "release"
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor
template: |
  ## 🚀 What's New in v$RESOLVED_VERSION

  $CHANGES

  ## 📦 Installation

  ### macOS
  ```bash
  brew install AM-i-B-V/github-env-manager/github-env-manager
  ```

  ### Linux
  ```bash
  curl -fsSL https://raw.githubusercontent.com/AM-i-B-V/github-env-manager/main/scripts/install.sh | bash
  ```

  ### Windows
  ```powershell
  Invoke-Expression (Invoke-WebRequest -Uri "https://raw.githubusercontent.com/AM-i-B-V/github-env-manager/main/scripts/install.ps1" -UseBasicParsing).Content
  ```

  ## 🔧 Usage

  ```bash
  github-env-manager
  ```

  The application will open at http://localhost:8080

  ## 📋 Full Changelog

  $CHANGES
